name: Build and Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: App Settings JSON
        run: 'echo "$APP_SETTINGS" > appSettings.json'
        env:
          APP_SETTINGS: ${{ secrets.APP_SETTINGS }}
      - name: Build Project
        run: npm run build:prod
  deploy:
    name: Deploy
    runs-on: [ ubuntu-latest ]
    steps:
      - name: LS
        run: ls -al
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
